apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "5000"
    spec:
      containers:
        - name: python-app-container
          imagePullPolicy: Always
          image: aymenzarour/python-app:latest
          ports:
            - containerPort: 5000
          env:
          - name: PYTHONUNBUFFERED
            value: "1"
